# Generated by Django 3.1.2 on 2020-10-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование партнера')),
                ('api_key', models.CharField(max_length=100, verbose_name='ключ API')),
                ('api_url', models.CharField(max_length=100, verbose_name='API url')),
            ],
            options={
                'verbose_name': 'партнер',
                'verbose_name_plural': 'партнеры',
                'db_table': 'partners',
            },
        ),
    ]
